# Generated by Django 5.1.4 on 2024-12-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receivemail",
            name="mail",
            field=models.EmailField(max_length=255, unique=True, verbose_name="email"),
        ),
    ]
