# Generated by Django 5.1.4 on 2025-01-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0002_alter_receivemail_mail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attemptmailing",
            name="response",
            field=models.TextField(
                blank=True, null=True, verbose_name="Ответ почтового сервера"
            ),
        ),
        migrations.AlterField(
            model_name="attemptmailing",
            name="status",
            field=models.CharField(
                choices=[("Успешно", "Успешно"), ("Не успешно", "Не успешно")],
                max_length=15,
                verbose_name="Статус попытки",
            ),
        ),
    ]
