# Generated by Django 5.1.4 on 2025-01-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0004_alter_receivemail_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="end_sending",
            field=models.DateTimeField(
                blank=True,
                help_text="гггг-мм-дд чч:мм:сс",
                null=True,
                verbose_name="Дата окончания отправки",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="first_sending",
            field=models.DateTimeField(
                blank=True,
                help_text="гггг-мм-дд чч:мм:сс",
                null=True,
                verbose_name="Дата первой отправки",
            ),
        ),
    ]
